tz 11
mat1x228/java-filmorate pull request #7
Opened 2024-12-20 10:51 UTC by mat1x228

2024-12-21 11:57 UTC, tomattman requested changes
Привет, есть множество комментариев

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
обычно слой контроллера не смотрит напрямую на слой базы данных, и все взаимодействие происходит через слой сервиса т.е. контроллер вызывает метод у сервиса, который в свою очередь вызывает метод у хранилища

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmServiceImpl filmServiceImpl, UserServiceImpl userServiceImpl,
на класс можно повесить аннотацию @RequiredArgsConstructor и тогда автоматически создастся конструктор со всеми private final параметрами
и его не надо будет писать вручную, что очень удобно когда появляются новые зависимости, да и просто удобнее

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilms();
как уже писал выше, вызываем сервис а он уже вызывает хранилище

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film film = filmStorage.getFilmById(id);
обычно работа происходит немного другим способом
мы работаем через ошибки 
т.е. filmService в методе getFilmById проверяет на null и если null то кидает какую ни будь ошибку унаследованную от RuntimeException 
а на уровне контроллера есть обработчик ошибок который умеет обрабатывать все нужные типы ошибок (гугли controlleradvice spring )
и все что нам остается сделать в методе контроллера, это
return ResponseEntity.ok().body(filmService.getFilmById(id));

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film createdFilm = filmStorage.createFilm(film);
есть разные архитектуры приложений, и в зависимости от них, действия выполняются на разных уровнях, теперь когда у вас есть слой хранилища сервиса и контроллеров рекомендую сделать следующим образом
хранилище хранит данные, и возвращает их никакой дополнительной логики, разве что фильтрация и генерация id
сервис выполняет всю логику, т.е. все проверки, все дополнительные действия
контроллер работает только с уровнем веб т.е. принять запрос, вызвать нужный метод сервиса, завернуть ответ в нужный обьект и вернуть (ну и обработка ошибок, так, чтобы при ошибке возвращался нужный статус и нужое тело запроса)

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final UserServiceImpl userServiceImpl;
обычно если у тебя есть интерфейсы, то инжект идет именно через них, иначе они у тебя почти не имеют никакого смысла

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final FilmServiceImpl filmServiceImpl;
я уже писал про интерфейсы и RequiredArgsConstructor и про связь с хранилищем через сервис

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User userCreated = userStorage.createUser(user);
логику бы тоже на слой сервиса подвигать

тут комментарии будут все те же что и в другом контроллере

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends = new HashSet<>();
модификаторы доступа

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void addLike(Integer id) {
такие методы чаще все не добавляют, ибо они излишни, делаешь геттер на Set и на урвоне сервиса все т е же действия
user.getLikes().add(id);

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    void addLike(int filmId, int userId);
про интерфейсы в спринге

в ранних версиях интерфейсы были обязательны, теперь же они не сильно нужны, в ральных проектах для простых сервисов чаще всего ими не пользуются
интерфейсами пользуются только для случаев, когда должно быть несколько вариантов имплементации одного и того же сервиса, 
самый простой пример из практики, есть сервис, но он в зависимости от каких то параметров должен выполнять одни и те же действия но по разному, например есть сервис который подготавливает отчеты, и он может делать это по разному, например в pdf картинку, или писать во внешний сервис, и вот в таком случае обычно используют интерфейсы, один интерфейс ReportWriter а у него три имплементации, инжектим мы сразу все, но в зависимости от параметра вызываем метод одной из них

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    InMemoryFilmStorage filmStorage;
модификаторы доступа, и снова инжектим обычно по интерфейсам если они есть
ну и снова про RequiredArgsConstructor

инжектим по интерфейсам по следующей причине, сейчас если у тебя появится другая имплементация хранилища фильмов, тебе понадобится сделать ее, а так же залезть сюда, и добавить ее здесь, если же ты заинжектишь по интерфейсу, то когда ты добавишь новую имплементацию и удалишь старую, то для того чтобы все работало, в этом классе тебе ничего не надо будет заменять, все автоматически подтянется

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        Film film = filmStorage.getFilmById(filmId);
смотри как делают гораздо чаще
делаешь так, чтобы храниkbще пользователtй возвращало не самого юзера а Optional<User>
и тогда можно сделать следующий метод
private User getUser(Long id) {
return userStroage.getUserById(id).orElseThrow(()-> new NotFoundException("пользователь не найден"))
}

и если ты вызовешь этот метод то или вернется пользователь (если тебе надо проверить только наличие, ответ можно игнорировать) или выкенется ошибка (которую можно отловить на уровне контроллера и сформировать нужный ответ)
конечно обротку ошибки и саму ошибку надо тоже будет написать

но при этом код становится гораздо чище

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +    InMemoryUserStorage userStorage;
все то же что и в другом сервисе

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +            throw new NotFoundException("Фильм не найден");
обычно ошибка кидается на уровне сервиса, тут же рекомендую сделать чтобы возвращался Optional<Film> 
и сделать просто return Optional.ofNullable(filmStorage.get(id));
ну и вся логика что я писал выше

2024-12-21 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryUserStorage.java
> +    public User getUserById(int id) {
аналогично

2025-01-06 14:29 UTC, mat1x228 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        Film film = filmStorage.getFilmById(filmId);
Можно пожалуйста этот момент поправить в рамках ТЗ12 ? Время поджимает

2025-01-06 14:29 UTC, mat1x228 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +            throw new NotFoundException("Фильм не найден");
поправлю вместе с моментом выше

2025-01-06 14:58 UTC, tomattman approved these changes
Принято

2025-01-06 14:58 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        Film film = filmStorage.getFilmById(filmId);
Конечно, это рекомендация

2025-01-06 20:02 UTC, merged